apiVersion: 'eksctl.io/v1alpha5'
kind: ClusterConfig
metadata:
  name: JEJU-DEV-ESB-CLUSTER
  region: us-east-2
  version: '1.19'
vpc:
  cidr: "172.31.0.0/16" # 클러스터에서 사용할 VPC의 CIDR
  clusterEndpoints:
    publicAccess: true
    privateAccess: true
managedNodeGroups:
  - name: JEJU-DEV-ESB-CLUSTER-NG # 클러스터의 노드 그룹명
    instanceType: t3.medium
    desiredCapacity: 2
    volumeSize: 10
    iam:
      withAddonPolicies:
        ImageBuilder: true # AWS ECR에 대한 권한 추가
        albIngress: true  # alb ingress에 대한 권한 추가
    ssh:
      allow: true # 워커 노드에 SSH 접속 허용
      publicKeyName: ESB-KEY-PAIR # 워커 노드에 SSH 접속을 위해 사용할 pem키 명(aws key pairs에 등록되어 있어야함)

